# Generated by Django 5.1 on 2024-09-02 21:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Applicant',
            new_name='Application',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
