# Generated by Django 5.1 on 2024-09-02 21:50

import organizations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='staff_access_code',
            field=models.CharField(default=organizations.models.generate_access_code, max_length=3, unique=True),
        ),
    ]
